 <h2><?=$this->channelTitle?></h2>
 
 <?php $i=1;foreach ($this->channel as $item): ?>
 
 <br/><br/>
    <h3><?=$item->title(); ?>&nbsp;&nbsp;<span style="font-size:12px;"><?=$item->pubDate() ?></span></h3>
    <p><?=$item->description() ?></p>
    <a href="<?=$item->link(); ?>"><?=$item->link(); ?></a><br><br/>
   
   <span style="font-size:18px;"><a href="<?=$this->baseUrl(); ?><?=$this->url(array('controller'=>'feed', 'action' => 'save' )).'?uid='.md5($item->guid()) ?>">SAVE</a>
   <span style="font-size:12px;"><?=$item->guid() ?></span><br>
    
   <hr />
    

<?php endforeach ?>
        
