<?php

require_once dirname(__FILE__) . '/../../../../../../content/_backup/demosZend/Gdata/InstallationChecker.php';

/**
 * Test class for InstallationChecker.
 * Generated by PHPUnit on 2011-07-02 at 16:22:09.
 */
class InstallationCheckerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var InstallationChecker
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new InstallationChecker;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @todo Implement testRunningInCLIMode().
     */
    public function testRunningInCLIMode() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testRunAllVerifications().
     */
    public function testRunAllVerifications() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testOutputResults().
     */
    public function testOutputResults() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
