
					<table>
						<caption><?= $this->message ?></caption>
						<thead>
						   <tr>
							<td>Privilege</td>
							<td>Allowed</td>
							<td>Resource</td>
							<td>Role</td>
							<td width="24"><small class="small">Edit</small></td>
							<td width="24"><small class="small">Delete</small></td>
							</tr>
						</thead>
						<?php  $endClass=''; foreach($this->privileges as $key => $privilege) : ?>
						<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $privilege->getId())); ?>"><?=$privilege->getPrivilegetype()->getName(); ?></a></td>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $privilege->getId())); ?>"><?=$privilege->getAllowed(); ?></a></td>
							
						<?php 
						    $resource=$privilege->getResource();
						    if(!empty($resource)){
						    	$resourceName=$resource->getType().":".$resource->getName();
						    	
						    }else{
						    	$resourceName='default';
						    }
						
						?>	
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $privilege->getId())); ?>"><?=$resourceName;?></a></td>
						<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $privilege->getId())); ?>"><?=$privilege->getRole()->getName(); ?></a></td>
						
							<td><a class="ui-icon ui-icon-pencil" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'edit', 'id' => $privilege->getId())); ?>">Edit</a></td>
							<td><a class="ui-icon ui-icon-close" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'delete', 'id' => $privilege->getId())); ?>">delete</a></td>
						</tr>
						<?php  $endClass=($key%2 == 1)?'class="even"':''; endforeach; ?>
						<tr <?php echo $endClass;?>>
							<td colspan="4"><a href="<?=$this->url(array('module' => 'CMSCore', 'controller' => 'index','action' => 'index')); ?>">Back</a></td>
							<td><a href="<?=$this->url(array('action' => 'create')); ?>">new</a></td>
						</tr>
					</table>
