<?php

require_once dirname(__FILE__) . '/../../../../../_backup/application/models/AuthenticationService.php';

/**
 * Test class for Application_Model_AuthenticationService.
 * Generated by PHPUnit on 2011-07-02 at 16:22:07.
 */
class Application_Model_AuthenticationServiceTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Application_Model_AuthenticationService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Application_Model_AuthenticationService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @todo Implement testAuthenticate().
     */
    public function testAuthenticate() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
