<?php echo $this->doctype() ?>
<html>
    <head>
        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
    </head>
    <body>
        <div id="content-page">
            <?php echo $this->render('_header.phtml') ?>
            <?php echo $this->layout()->content ?>
            <?php echo $this->render('_footer.phtml') ?>
        </div>
    </body>
</html>