<?= $this->doctype() . "\r\n"; ?>
<html lang="<?= $this->placeholder('locale'); ?>" class="no-js <?= $this->placeholder('htmlclasses'); ?>">
	<head>
        <?=$this->headTitle(); ?>
        <?=$this->headMeta(); ?>
        <?=$this->headLink(); ?>
        <?=$this->headStyle(); ?>
        <?='';//$this->render('includes/head.phtml'); ?>
	</head>
	<body>
        <div class="container-fluid">
            <div class="row-fluid">
                <?=$this->render('page.header.phtml'); ?>
            </div>
            <div class="row-fluid">
                <div class="span2">
                <!--Sidebar content-->
                <?=$this->layout()->sidepanel;//$this->render('page.sidepanel.phtml'); ?>
                </div>
                <div class="span10">
                <article>
                <?=$this->layout()->content; ?>
                </article>
                </div>
            </div>
            <div class="row-fluid">
                <?=$this->render('page.footer.phtml'); ?>
            </div>
            <div id="screen-offset">
                <?='';//$this->renderPartials('partials/manager/modal.*.phtml'); ?>
                <?='';//$this->render('includes/scripts.phtml'); ?>
            </div>
        </div>

	</body>

</html>
