<?=$this->doctype() ?>
<html>
    <head>
        <?=$this->headTitle(); ?>
        <?=$this->headMeta(); ?>
        <?=$this->headLink(); ?>
        <?=$this->headStyle(); ?>
    </head>
    <body>
        <section id="wrapper">
            <?=$this->render('page.header.phtml'); ?>
            <article id="content">
                <?=$this->layout()->content; ?>
            </article>
            <?=$this->render('page.footer.phtml'); ?>
    	</section>
    </body>
</html>