<?= $this->doctype() . "\r\n"; ?>
<html lang="<?= $this->placeholder('locale'); ?>" class="no-js <?= $this->placeholder('htmlclasses'); ?>">
	<head>
        <?=$this->headTitle(); ?>
        <?=$this->headMeta(); ?>
        <?=$this->headLink(); ?>
        <?=$this->headStyle(); ?>
        <?='';//$this->render('includes/head.phtml'); ?>
	</head>
	<body>

        <div class="container-fluid">
            <div class="row-fluid">
                <div class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            <a class="brand" href="#">Skeleton Application</a>
                            <div class="nav-collapse">
                                <ul class="nav">
                                    <li class="active"><a href="#">Home</a></li>
                                </ul>
                            </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="row-fluid">
                <?=$this->render('page.header.phtml'); ?>
            </div>
            <div class="row-fluid">
                <div class="span2">
                <!--Sidebar content-->
                <?=$this->layout()->sidepanel; ?>
                </div>
                <div class="span10">
                <article>
                <?=$this->layout()->content; ?>
                </article>
                </div>
            </div>
            <hr />
            <footer class="row-fluid">
                <?=$this->render('page.footer.phtml'); ?>
            </footer>
        </div>

	</body>

</html>
