<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
<tr>
    <td><input type="checkbox" id="page-<?=$this->entity->id; ?>" name="categories" value="<?=$this->entity->id; ?>" /></td>
    <td><a href="/manager/categories/update/<?=$this->entity->id; ?>"><?=($this->entity->title!='')?$this->entity->title:'title'; ?></a></td>
    <td><?=$this->entity->parent->title; ?></td>
    <td><a class="btn danger delete pull-right" href="/manager/categories/delete/<?=$this->entity->id; ?>">delete</a></td>
</tr>
