<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            <td><input type="checkbox" id="page-<?=$this->entity->id; ?>" name="contactlocations" value="<?=$this->entity->id; ?>" /></td>
            <td><a href="/manager/contactlocations/update/<?=$this->entity->id; ?>"><?=($this->entity->name!='')?$this->entity->name:'name'; ?></a></td>
            <td><?="";?></td>
            <td><?="";//$this->entity->listCategories();?></td>
            <td><?php

            ?></td>
            <td><a class="btn danger delete pull-right" href="/manager/contactlocations/delete/<?=$this->entity->id; ?>">delete</a></td>
        </tr>