<?php

/*
 * Basic Entity List.
 */

?>
                <tr>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/update/<?=$this->entity->id; ?>"><?=$this->entity->title; ?></a></td>
                    <td><?="";?></td>
                    <td><?="";?></td>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/update/<?=$this->entity->id; ?>">update</a></td>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/delete/<?=$this->entity->id; ?>">delete</a></td>
                </tr>