<?php
//    $this->entity->setTranslatableLocale($this->placeholder('locale'));
//    $this->placeholder('doctrine')->em->refresh($this->entity);
?>
<tr>
    <td><input type="checkbox" id="hcard-<?=$this->entity->id; ?>" name="hcard" value="<?=$this->entity->id; ?>" /></td>
    <td><a href="/admin/hcard/update/<?=$this->entity->id; ?>"><?=$this->entity->getFullName();?></a></td>
    <td><?=$this->entity->brand->title;?></td>
    <td><?="";//$this->entity->listCategories();?></td>
    <td><?=$this->entity->listTags();?></td>
</tr>
