<div id="confirm-deletion" class="modal hide fade">
    <div class="modal-header">
        <a href="#" class="close">&times;</a>
        <h2>Confirm Deletion</h2>
    </div>
    <div class="modal-body">
        <p>Are you sure you want to delete the checked item(s)?</p>
    </div>
    
    <div class="modal-footer">
        <a href="#" class="btn danger modal-confirm">Delete</a>
        <a href="#" class="btn secondary modal-exit">Cancel</a>
    </div>
</div>