<div id="asset-manager" class="modal hide fade">
    <div class="modal-body">
        <p>Content loading &hellip;</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn primary modal-confirm" data-placement="above" rel="twipsy" title="Some title text">Save Changes</button>
        <button type="button" class="btn secondary modal-close" data-placement="above" rel="twipsy" title="Some title text">Close</button>
    </div>
</div>