<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            
            <td><a href="/admin/stores/update/<?php echo $this->entity->id; ?>"><?php echo ($this->entity->title!='')?$this->entity->title:'title'; ?></a></td>
            <td><a class="btn danger delete pull-right" href="/admin/stores/delete/<?php echo $this->entity->id; ?>">delete</a></td>
        </tr>