
                <tr>
                    <th title="Select"></th>
                    <th title="This is the user's firstname.">Firstname</th>
                    <th title="This is the user's lastname.">Lastname</th>
                    <th></th>
                    <th title="This is the user's email address">Email</th>
                    <th title="This is the user's gravatar image"></th>
                    <th title="This is the user's roles">Role</th>
                </tr>
