<tr>
    <td><input type="checkbox" id="page-<?=$this->entity->id; ?>" name="page" value="<?=$this->entity->id; ?>" /></td>
    <td><a href="/admin/users/update/<?=$this->entity->id; ?>"><?=($this->entity->firstname!='')?$this->entity->firstname:'not set';?></a></td>
    <td><?=($this->entity->lastname!='')?$this->entity->lastname:'not set';?></td>
    <td><?php /*
    $userGroups = "";
    foreach($this->entity->acluserroles as $role){
        foreach ($role->brands as $brand) {
            $userGroups .= "".$brand->title.", ";
        }
    }
    ?><?=$userGroups*/?><?=$this->entity->brand->title?></td>
    <td><?=$this->entity->email?></td>
    <td><?=$this->gravatar($this->entity->email)->setImgSize(32)->setAttribs(array('class' => 'avatar', 'title' => $this->entity->username));?></td>
    <td><?php
    $userGroups = "";
    foreach($this->entity->acluserroles as $role){
        $userGroups .= "".str_replace("_"," ",$role->title).", ";
    }
    $userGroups = rtrim($userGroups,", ");
    ?><?=$userGroups;?></td>
</tr>
