<?php

namespace Application\Entities;

require_once dirname(__FILE__) . '/../../../../../../application/modules/default/entities/Permissions.php';

/**
 * Test class for Permissions.
 * Generated by PHPUnit on 2011-07-02 at 16:23:24.
 */
class PermissionsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Permissions
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Permissions;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @todo Implement testGetId().
     */
    public function testGetId() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetAllowed().
     */
    public function testSetAllowed() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetAllowed().
     */
    public function testGetAllowed() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testAddRole().
     */
    public function testAddRole() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetRole().
     */
    public function testGetRole() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetAction().
     */
    public function testSetAction() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetAction().
     */
    public function testGetAction() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
