<?php

namespace Application\Entities;

require_once dirname(__FILE__) . '/../../../../../../application/modules/default/entities/Roles.php';

/**
 * Test class for Roles.
 * Generated by PHPUnit on 2011-07-02 at 16:23:24.
 */
class RolesTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Roles
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Roles;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
	
    }

    /**
     * @todo Implement testGetId().
     */
    public function testGetId() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetName().
     */
    public function testSetName() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetName().
     */
    public function testGetName() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetDescription().
     */
    public function testSetDescription() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetDescription().
     */
    public function testGetDescription() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testAddPermission().
     */
    public function testAddPermission() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetPermission().
     */
    public function testGetPermission() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetParent().
     */
    public function testSetParent() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetParent().
     */
    public function testGetParent() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testSetBuildOrder().
     */
    public function testSetBuildOrder() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @todo Implement testGetBuildOrder().
     */
    public function testGetBuildOrder() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
