<li class="ui-state-default resource" id="gallery_<?=$this->entity->id;?>">
    <span class="count"></span>
    <!--
    <button type="button" class="ui-icon ui-icon-search media-info">View further information on this asset</button>
    -->
    <button type="button" class="ui-icon ui-icon-close media-remove">Remove featured image</button>
    <!--
    <button type="button" class="ui-icon ui-icon-scissors media-edit">Edit</button>
    -->
    <a href="#">

<!--        <img class="logo" alt="Logo" src="/cms-logo.jpg">-->
<!--        <img class="thumbnail" width="95" height="95" title="<?=$this->entity->title?>" alt="<?=$this->entity->summary;?>" src="<?//=$this->resource($this->entity->resource,array('render'=>'uri','size'=>'homepagesmall'));?>" data-id="<?=$this->entity->resource->id;?>">-->
        <img class="thumbnail" width="95" height="95" title="<?=$this->entity->title?>" alt="<?=$this->entity->summary;?>" src="<?=$this->entity->link;?>" data-id="<?=$this->entity->id;?>">
        <?//=$this->resource($this->entity->resource,array('renderer' => 'html', 'class' => 'thumbnail', 'height' => '95', 'width' => '95'));?>
    </a>
</li>