<div class="media-grid featured clearfix">
    <div class="ui-state-default resource" id="gallery_<?=$this->entity->resource->id;?>" data-title="<?=$this->entity->resource->title;?>">
        <!--
        <span class="count"></span>
        <button type="button" class="ui-icon ui-icon-search media-info">View further information on this asset</button>
        -->
        <button type="button" class="ui-icon ui-icon-close media-remove">Remove featured image</button>
        <!--
        <button type="button" class="ui-icon ui-icon-scissors media-edit">Edit</button>
        -->
        <a href="#">
            <?=$this->resource($this->entity->resource,array('renderer' => 'html', 'class' => 'thumbnail', 'height' => '230', 'width' => '320'));?>
        </a>
    </div>
</div>