<li class="ui-state-default resource" id="gallery_<?=$this->entity->resource->id;?>">
    <span class="count"></span>
    <!--
    <button type="button" class="ui-icon ui-icon-search media-info">View further information on this asset</button>
    -->
    <button type="button" class="ui-icon ui-icon-close media-remove">Remove featured image</button>
    <!--
    <button type="button" class="ui-icon ui-icon-scissors media-edit">Edit</button>
    -->
    <a href="#">
        <?=$this->resource($this->entity->resource,array('renderer' => 'html', 'class' => 'thumbnail', 'height' => '95', 'width' => '95'));?>
    </a>
</li>