<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            <td><a href="/manager/newsitems/update/<?=$this->entity->id; ?>"><?=($this->entity->title!='')?$this->entity->title:'Address'; ?></a></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><a href="/manager/newsitems/delete/<?=$this->entity->id; ?>">delete</a></td>
        </tr>
