
					<table>
						<caption><?= $this->message ?></caption>
						<thead>
							<td>Name</td>
							<td>Description</td>
							<td>Parent</td>
							<td width="24"><small class="small">Edit</small></td>
							<td width="24"><small class="small">Delete</small></td>
						</thead>
						  
					
						<?php foreach($this->roles as $key => $role) : ?>
						<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $role->getId())); ?>"><?=$role->getname(); ?></a></td>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $role->getId())); ?>"><?=$role->getDescription(); ?></a></td>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $role->getId())); ?>"><?=$role->getParent()->getName(); ?></a></td>
								
							<td><a class="ui-icon ui-icon-pencil" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'edit', 'id' => $role->getId())); ?>">Edit</a></td>
							<td><a class="ui-icon ui-icon-close" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'delete', 'id' => $role->getId())); ?>">delete</a></td>
						</tr>
						
						<?php endforeach; ?>
						
						<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
							<td colspan="4"><a href="<?=$this->url(array('module' => 'CMSCore', 'controller' => 'index','action' => 'index')); ?>">Back</a></td>
							<td><a href="<?=$this->url(array('action' => 'create')); ?>">new</a></td>
						</tr>
					</table>
