		<?= $this->headTitle($this->title)->setIndent("\t\t")."\r\n"; ?>

		<!--[if IE 6 ]>
			<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<![endif]-->

        <?= $this->headMeta()->setIndent("\t\t")."\r\n"; ?>

        <link rel="shortcut icon" href="<?= $this->theme->themePath . 'img/branding/favicon.ico'; ?>" />
        <link rel="apple-touch-icon" href="<?= $this->theme->themePath . 'img/branding/apple-touch-icon-72x72.png'; ?>" />
        <link rel="apple-touch-icon" sizes="72x72" href="<?= $this->theme->themePath . 'img/branding/apple-touch-icon-72x72.png'; ?>" />
        <link rel="apple-touch-icon" sizes="114x114" href="<?= $this->theme->themePath . 'img/branding/apple-touch-icon-114x114.png'; ?>" />

        <link href="http://microformats.org/profile/hatom" rel="profile" />
        <link href="http://microformats.org/profile/hcard" rel="profile" />

        <link href="<?= $this->baseUrl('/admin'); ?>" rel="home" />

        <?= $this->headLink()->setIndent("\t\t")."\r\n"; ?>
        
        <?= $this->headStyle()->setIndent("\t\t")."\r\n"; ?>
        
        <?= $this->headScript()->setIndent("\t\t")."\r\n"; ?>

        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->