<div class="topbar" data-dropdown="dropdown">

    <div class="topbar-inner">

        <div class="container-fluid">

            <a class="brand" href="<?= $this->baseUrl('/admin'); ?>"><?= $this->placeholder('site')->clientname; ?></a>

            <?php if ($this->userIsLoggedIn()): ?>

                <ul class="nav">

                    <li class="menu locale-menu">
                        <a href="#" class="menu icon-flag icon-flag-<?php echo $this->admin_locale; ?> current-flag" rel="popover" data-content="Click here to pick another locale on which to edit content." data-original-title="Show locales menu">Switch Locale</a>
                        <ul class="menu-dropdown">
                            <?php echo $this->localeSwitcher(@$_REQUEST['admin_locale'], $this->available_locales); ?>
                            <li class="divider"></li>
                            <li><a href="<?=$this->baseUrl('/admin'); ?>/locales-settings.php">Edit Locales</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav secondary-nav">
                    <?php if ($this->authorised('mvc:admin:users', 'Update')): ?>
                        <li class="menu users-menu"><a href="#" class="menu">Users</a>
                            <?=
                            $this->navigation()->menu()->renderMenu($this->placeholder('navigation')->permissions, array(
                                'ulClass' => 'menu-dropdown',
                                'maxDepth' => 1,
                                'minDepth' => 0,
                                'onlyActiveBranch' => false,
                                'renderParents' => false
                            ));
                            ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($this->authorised('mvc:admin:master:admin', 'Update')): ?>
                        <li class="menu advanced-menu"><a href="#" class="menu">Metadata</a>
                            <?=
                            $this->navigation()->menu()->renderMenu($this->placeholder('navigation')->metadata, array(
                                'ulClass' => 'menu-dropdown',
                                'maxDepth' => 1,
                                'minDepth' => 0,
                                'onlyActiveBranch' => false,
                                'renderParents' => false
                            ));
                            ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($this->authorised('mvc:admin:master:admin', 'Update')): ?>
                        <li class="menu advanced-menu"><a href="#" class="menu">Assets</a>
                            <?=
                            $this->navigation()->menu()->renderMenu($this->placeholder('navigation')->assets, array(
                                'ulClass' => 'menu-dropdown',
                                'maxDepth' => 1,
                                'minDepth' => 0,
                                'onlyActiveBranch' => false,
                                'renderParents' => false
                            ));
                            ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($this->authorised('mvc:admin:master:admin', 'Update')): ?>
                        <li class="menu advanced-menu"><a href="#" class="menu">Content</a>
                            <?=
                            $this->navigation()->menu()->renderMenu($this->placeholder('navigation')->content, array(
                                'ulClass' => 'menu-dropdown',
                                'maxDepth' => 2,
                                'minDepth' => 0,
                                'onlyActiveBranch' => false,
                                'renderParents' => false
                            ));
                            ?>
                        </li>
                        <?php endif; ?>
                        <?php if ($this->authorised('mvc:admin:master:admin', 'Update')): ?>
                        <li class="menu advanced-menu"><a href="#" class="menu">Advanced</a>
                        <?=
                        $this->navigation()->menu()->renderMenu($this->placeholder('navigation')->advanced, array(
                            'ulClass' => 'menu-dropdown',
                            'maxDepth' => 1,
                            'minDepth' => 0,
                            'onlyActiveBranch' => false,
                            'renderParents' => false
                        ));
                        ?>
                        </li>
                        <?php endif; ?>
                    <li class="menu account-menu">
                        Logged in as <a href="#" class="menu"><?= $this->currentUser()->username; ?></a>
                        <ul class="menu-dropdown">
                            <li><a href="<?= $this->baseUrl('/admin/users/update/' . $this->currentUser()->id); ?>">Account Settings</a></li>
                            <li class="divider"></li>
                            <li><a href="<?= $this->baseUrl('/admin/auth/logout'); ?>">Log Out</a></li>
                        </ul>
                    </li>
                </ul>

<?php endif; ?>

        </div>

    </div>

</div>