<ul class="breadcrumb">
    <?php if($this->url() == $this->baseUrl('/admin')): ?>
        <li>Home</li>
    <?php else: ?>
        <li><a rel="twipsy" href="<?= $this->baseUrl('/admin'); ?>" title="Go to the home screen">Home</a><span class="divider">/</span></li>
    <?php endif; ?>
    <?= $this->navigation()
    //$this->navigation($this->layout()->globalNavigation)
    ->breadcrumbs()
    ->setMinDepth(0)
    //->setLinkLast(true)
//    ->setSeparator(":");        
    ->setSeparator('<span class="divider">/</span>' . PHP_EOL);
//    ->render(); 
    ?>
        
       
        <?php
//        
//        $container = new Zend_Navigation();
//        $this->navigation($this->layout()->breadcrumbs);
//            echo 'You are in: '.$this->navigation()->breadcrumbs()->setLinkLast(false)->setMinDepth(0)->render();
            
        ?>
</ul>