<aside id="side-panel" class="closed">

    <div class="browser-tree">
        <span>Loading tree browser &hellip;</span>
        <ul>
            <li id="rhtml_1" class="jstree-open" data-uid="1234">
                <a href="#">Root node 1</a>
                <ul>
                    <li id="rhtml_2" data-uid="4366">
                        <a href="#">Child node 1</a>
                    </li>
                    <li id="rhtml_3" data-uid="8525">
                        <a href="#">Child node 2</a>
                    </li>
                </ul>
            </li>
            <li id="rhtml_4"  data-uid="3784">
                <a href="#">Root node 2</a>
            </li>
        </ul>
    </div>

</aside>