<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>
                <tr>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/update/<?=$this->entity->id; ?>"><?=$this->entity->title; ?></a></td>
                    <td>Author</td>
                    <td><?="";/*$this->entity->getTags();*/ ?></td>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/update/<?=$this->entity->id; ?>">update</a></td>
                    <td><a href="<?= $this->placeholder('currenturi'); ?>/delete/<?=$this->entity->id; ?>">delete</a></td>
                </tr>