<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            <td><a href="/manager/pages/update/<?=$this->entity->id; ?>"><?=($this->entity->title!='')?$this->entity->title:$this->entity->slug; ?></a></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?=$this->entity->slug; ?></td>
            <td><a href="/manager/pages/delete/<?=$this->entity->id; ?>">delete</a></td>
        </tr>
