<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            <td><a href="/admin/templates/update/<?=$this->entity->id; ?>"><?=($this->entity->title!='')?$this->entity->title:'title'; ?></a></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><a href="/admin/templates/delete/<?=$this->entity->id; ?>">delete</a></td>
        </tr>
