					<div class="clearfix">
						<h1><?=$this->title?></h1>
						<?php if ($this->message): ?>
							<p>The following error occurred:</p>
							<pre><?=$this->message ?></pre>
						<?php endif; ?>
						<?php if (isset($this->exception)): ?>
							<h3>Exception information:</h3>
							<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

							<h3>Stack trace:</h3>
							<pre><?php echo $this->exception->getTraceAsString() ?></pre>

							<h3>Request Parameters:</h3>
							<pre><?php echo var_export($this->request->getParams(), true) ?></pre>
						<?php endif ?>
					</div>
