

					<table>
						<caption><?= $this->message ?></caption>
						<thead>
							<td>Name</td>
							<td>Permission</td>
							<td width="24"><small class="small">Edit</small></td>
							<td width="24"><small class="small">Delete</small></td>
						</thead>
						<?php foreach($this->permissions as $key => $permission) : ?>
						<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
							<?php 
								$action = $permission->getAction();
								$allowed = ($permission->getAllowed()==1)?'allowed':'denied';
							?>
							<td><a href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'view', 'id' => $permission->getId())); ?>"><?=$action->getName()?></a></td>
							<td><?=$allowed?></td>
							<td><a class="ui-icon ui-icon-pencil" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'edit', 'id' => $permission->getId())); ?>">Edit</a></td>
							<td><a class="ui-icon ui-icon-close" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'delete', 'id' => $permission->getId())); ?>">delete</a></td>
						</tr>
						<?php endforeach; ?>
						<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
							<td colspan="3"><a href="<?=$this->url(array('module' => 'CMSCore', 'controller' => 'index','action' => 'index')); ?>">Back</a></td>
							<td><a href="<?=$this->url(array('action' => 'create')); ?>">new</a></td>
						</tr>
					</table>
					