
                    <tr>
                        <th title="Select"></th>
                        <th title="This is the the collections name.">Name</th>
                        <th title="This is the the collections season.">Season</th>
                        <th title="This is the the collections year.">Year</th>
                        <th></th>
                        <th></th>
                        <th title="Remove"></th>
                    </tr>
