<?php
//$this->entity->setTranslatableLocale($this->placeholder('locale'));
//$this->placeholder('doctrine')->em->refresh($this->entity);
?>
        <tr>
            <td><input type="checkbox" id="page-<?=$this->entity->id; ?>" name="settings" value="<?=$this->entity->id; ?>" /></td>
            <td><a href="/admin/manage/looks/update/<?=$this->entity->id; ?>/<?=$this->entity->products->first()->collection->slug; ?>"><?=($this->entity->title!='')?$this->entity->title:'title'; ?></a></td>
            <td><?=$this->entity->products->first()->collection->title; ?></td>
            <td><?="";?></td>
            <td><?="";?></td>
            <td><a class="btn danger delete pull-right" href="/manager/manage/looks/delete/<?=$this->entity->id; ?>">delete</a></td>
        </tr>
