
                    <tr>
                        <th title="Select"></th>
                        <th title="This is the the seasons name.">Name</th>
                        <th title="This is the the seasons season.">Season</th>
                        <th title="This is the the seasons year.">Year</th>
                        <th></th>
                        <th></th>
                        <th title="Remove"></th>
                    </tr>
