        <?= $this->ckeditor ?>
		<?= $this->form ?>
		<hr />
		<h4><?= $this->messages ?></h4>
<?php if(isset($this->versions)) : ?>
  
	
	<table id="versiontable_id">
		<caption>Version History</caption>
		<thead>
			<td>Version</td>
			<td>Publish Version</td>
			<td>Version Date</td>
			<td width="24"><small class="small">RollBack</small></td>
			<td width="24"><small class="small">Delete</small></td>
		</thead>
		<tbody>
			<?php $key=1;foreach($this->versions as $key => $version) : ?>
			<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
				<td><?=$version->getVersion();?></td>
		        <td><?=$version->getPublishVersion();?></td>
		        <td><?=$version->getSnapshotDate()->format("d M Y  H:i");?></td>
			    	
				<td><a class="ui-icon ui-icon-star" title="roll back" href="#" onclick="return rollback('<?=$this->contentId;?>','<?=$version->getVersion();?>');" >rollback</a></td>
				<td><a class="ui-icon ui-icon-close" title="delete" href="<?=$this->baseUrl(); ?><?=$this->url(array('action' => 'delete', 'id' => $version->getId())); ?>?contentid=<?=$this->contentId;?>">delete</a></td>
			</tr>
			<?php endforeach; ?>
			<tr <?php echo ($key%2 == 1)?'class="even"':'';?>>
				<td colspan="4"><a href="<?=$this->url(array('module' => 'CMSCore', 'controller' => 'pages','action' => 'index')); ?>">Back</a></td>
				<td><a href="<?=$this->url(array('action' => 'create')); ?>">new</a></td>
			</tr>
		</tbody>
	 </table>
	
<?php else: ?>
    <h2>Listing Unknow Page Contents</h2>
    <p>No Results</p>
<?php endif; ?>

		