
			<!--STRUCTURE: CONTENT START-->
			<div class="structure" id="content">
				<a class="navigation named-anchor" id="content-anchor"></a>


				<h1 class="screen-offset">H1: Moncler</h1>


				<!--TAPESTRY START-->
				<div class="grid-flexible-container tapestry" id="state-16" data-instruction-display-duration="3"><script type="text/javascript">document.getElementById("state-16").id='state-1';</script>


					<!--SPOTLIGHT 1 START-->
					<div class="grid" id="spotlight-1">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-partial-fade">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->commerceSite('/moncler/home/realgender/man/tskay/1B23EDB7/gender/U/agerange/Adult');?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<?=$this->placeholder('translate')->translate->_('The Moncler e&#8209store');?>
												
											</h4>
											<p class="action navigation">
												<em><?=$this->placeholder('translate')->translate->_('Open 24/7');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 1 END-->


					<!--SPOTLIGHT 2 START-->
					<div class="grid" id="spotlight-2">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/campaigns/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em>Moncler <?=$this->placeholder('translate')->translate->_('by');?> Bruce Weber</em>
											</h4>
											<p class="action navigation">
<!--												<em>News</em>-->
												<em><?=$this->placeholder('translate')->translate->_('View the campaign');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 2 END-->


					<!--SPOTLIGHT 3 START-->
					<div class="grid" id="spotlight-3">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-portrait">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/moncler-s/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">

											<h4>
												<em>Moncler S</em>
											</h4>
											<p class="action navigation">
												<em><?=$this->placeholder('translate')->translate->_('View the FW11 Collection');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 3 END-->


					<!--SPOTLIGHT 4 START-->
					<div class="grid" id="spotlight-4">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-partial-fade">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/moncler-grenoble/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												Moncler Grenoble
											</h4>
											<p class="action navigation">
<!--												View the collection-->
												<em><?=$this->placeholder('translate')->translate->_('View the FW11 Collection');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 4 END-->


					<!--SPOTLIGHT 5 START-->
					<div class="grid" id="spotlight-5">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-portrait">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/moncler-v/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
											    <em>Moncler V</em>
											</h4>
											<p class="action navigation">
<!--												<em>View the collection</em>-->
												<em><?=$this->placeholder('translate')->translate->_('View the FW11 Collection');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 5 END-->


					<!--SPOTLIGHT 6 START-->
					<div class="grid" id="spotlight-6">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/moncler-gamme-bleu/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em>Moncler <br />Gamme Bleu</em>
											</h4>
											<p class="action navigation">
<!--												<em>View the collection</em>-->
												<em><?=$this->placeholder('translate')->translate->_('View the FW11 Collection');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 6 END-->


					<!--SPOTLIGHT 7 START-->
					<div class="grid" id="spotlight-7">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/campaigns-gamme-rouge/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em>Moncler <br />Gamme Rouge <?=$this->placeholder('translate')->translate->_('by');?><br /> Steven Meisel</em>
											</h4>
											<p class="action navigation">
<!--												<em>View all images</em>-->
												<em><?=$this->placeholder('translate')->translate->_('View the FW11 Campaign');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 7 END-->


					<!--SPOTLIGHT 8 START-->
					<div class="grid" id="spotlight-8">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/stores/'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em><?=$this->placeholder('translate')->translate->_('Now Open');?></em>
											</h4>
											<p class="action navigation">
<!--												<em>The Moncler stores</em>-->
												<em><?=$this->placeholder('translate')->translate->_('Locate our stores');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 8 END-->


					<!--SPOTLIGHT 9 START-->
					<div class="grid" id="spotlight-9">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/collections/moncler-womens-accessories'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em>Moncler<br /> a&#8209;Porter</em>
											</h4>
											<p class="action navigation">
<!--												<em>Shop accessories</em>-->
												<em><?=$this->placeholder('translate')->translate->_('Shop Accessories');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 9 END-->


					<!--SPOTLIGHT 10 START-->
					<div class="grid" id="spotlight-10">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-partial-fade">

							<!--OVERLAY LINK START-->
							<a class="overlay-link fancybox" href="<?= $this->baseUrl('/index/signup'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content ">
											<h4>
												<?=$this->placeholder('translate')->translate->_('Email Signup');?>
											</h4>
											<p class="action navigation">
											    <em><?=$this->placeholder('translate')->translate->_('Get the latest from Moncler');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 10 END-->


					<!--SPOTLIGHT 11 START-->
					<div class="grid" id="spotlight-11">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-portrait">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/news/latest/?articleId=all-time-friends-of-moncler'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em><?=$this->placeholder('translate')->translate->_('Friends of');?> Moncler</em>
											</h4>
											<p class="action navigation">
												<em><?=$this->placeholder('translate')->translate->_('See who\'s with us');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 11 END-->



					<!--SPOTLIGHT 12 START-->
					<div class="grid" id="spotlight-12">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-partial-fade">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->commerceSite('/moncler/home/realgender/woman/tskay/1B23EDB7/gender/D/agerange/Adult');?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												Moncler
											</h4>
											<p class="action navigation">
<!--												<em>Shop Womens</em>-->
												<em><?=$this->placeholder('translate')->translate->_('Shop Womens');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 12 END-->



					<!--SPOTLIGHT 13 START-->
					<div class="grid" id="spotlight-13">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->commerceSite('/moncler/home/realgender/woman/tskay/1B23EDB7/gender/D/agerange/Adult');?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em><?=$this->placeholder('translate')->translate->_('Shop the Beijing Store Window');?></em>
											</h4>
											<p class="action navigation">
<!--												<em>Shop Mens</em>-->
												<em><?=$this->placeholder('translate')->translate->_('Shop Womens');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 13 END-->


					<!--SPOTLIGHT 14 START-->
					<div class="grid" id="spotlight-14">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/news/latest/?articleId=the-doudoune-elastique'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em><?=$this->placeholder('translate')->translate->_('The Doudoune Elastique');?></em>
											</h4>
											<p class="action navigation">
<!--												<em>News</em>-->
												<em>Discover our new fabric</em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 14 END-->


					<!--SPOTLIGHT 15 START-->
					<div class="grid" id="spotlight-15">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0 config-partial-fade">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/news/latest/?articleId=moncler-is-turning-60'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												Moncler <?=$this->placeholder('translate')->translate->_('is turning 60');?>
											</h4>
											<p class="action navigation">
<!--												Discover our heritage-->
											    <em><?=$this->placeholder('translate')->translate->_('Countdown to our birthday');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 15 END-->


					<!--SPOTLIGHT 16 START-->
					<div class="grid" id="spotlight-16">

						<!--SPOTLIGHT START-->
						<div class="spotlight config-flicker config-overlay-shade-0">

							<!--OVERLAY LINK START-->
							<a class="overlay-link" href="<?= $this->baseUrl('/news/latest/?articleId=moncler-gamme-bleu-primavera-estate-2012'); ?>">
								<div class="faux-table">
									<div class="faux-table-cell">
										<div class="overlay-link-content">
											<h4>
												<em>Moncler <br />Gamme Bleu<br /> <?=$this->placeholder('translate')->translate->_('Goes Fencing');?></em>
											</h4>
											<p class="action navigation">
<!--												<em>Watch the show</em>-->
												<em><?=$this->placeholder('translate')->translate->_('Watch the show');?></em>
											</p>

										</div>
									</div>
								</div>
							</a>
							<!--OVERLAY LINK END-->

						</div>
						<!--SPOTLIGHT END-->

					</div>
					<!--SPOTLIGHT 16 END-->



				</div>
				<!--TAPESTRY END-->


			</div>
			<!--STRUCTURE: CONTENT END-->